# Generated by Django 6.1.1 on 2026-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionupdate',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
