# Generated by Django 5.2.8 on 2026-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
