# Generated by Django 6.1.1 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                max_length=200,
            ),
        ),
    ]
