# Generated by Django 6.1.1 on 2026-09-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
